### PR TITLE
Do timestamp production closer to event instrumentation sites

### PR DESCRIPTION
**Pull request by ZackPierce**
By producing timestamps (if not provided by the user) closer to the instrumentation site we incur the cost of a little extra work on the instrumented thread (to produce the system time), for the benefit of more precise timestamps that aren't offset due to the asynchronous nature of the ingest worker thread. 

The first commit also contains some alternate variants on the `monitored_pipeline` example demonstrating different ways of mixing nonce and timestamp based interaction annotation.  Removed in the second commit to keep the example clutter down.

### CODE REVIEW

**Comment by azdle** [comment]
My initial gut reaction is that I'd like to see the timestamp capture mirror (or replace) what is currently done for `tick`: https://github.com/auxoncorp/modality-tracing-rs/blob/master/tracing-modality/src/common/layer.rs#L61

I have to imagine that just always copying the current time into the struct would be faster than the hash lookup to check if we should and, at least IMO, is cleaner.

Thoughts?

**Comment by ZackPierce** [comment]
I disagree about the  "unconditionally clobbering the timestamp field" portion.  If the user has decided to provide a custom value for the `timestamp`, we should respect it, since they are in possession of richer context and understanding of the system being instrumented.

**Comment by azdle** [comment]
That's not what I'm suggesting.

I'm suggesting that we unconditionally fill a struct field on the trace'd thread, like tick: https://github.com/auxoncorp/modality-tracing-rs/blob/master/tracing-modality/src/common/layer.rs#L61

Then we do the implicit/explicit value choice along with all the other metadata that is already happening in the ingest thread, like tick: https://github.com/auxoncorp/modality-tracing-rs/blob/master/tracing-modality/src/common/ingest.rs#L449-L456

**Comment by azdle** [comment]
Hmm, tick is for some reason not actually checking for an explicit value on the ingest side, look at any of the other ones: Edit: like anything besides tick, I guess: https://github.com/auxoncorp/modality-tracing-rs/blob/master/tracing-modality/src/common/ingest.rs#L578-L586

**Comment by ZackPierce** [comment]
Okay, thank you for the clarification on clobbering.

Pros of unconditionally producing a timestamp as suggested:
* Central location of timestamp generation
* Remove one hash-table lookup

Cons:
* Do system-time calls per instrumentation activity even if that time info is definitely going to get ignored:
     * When the message is not getting turned into an event
     * When the message already contains a user-provided timestamp 
* The central location is a little further away from the point of instrumentation

I think that one hash table lookup in a small, in-cache table for *some* messages is probably a bit cheaper than system-timestamp generation *all* the time.  This is in no small part because getting the system time likely involves a syscall, and (even an efficient syscall that elides mode switches in some cases) is far from a free copy.

**Comment by ZackPierce** [comment]
That said, it's probably pretty close and there's something to be said for being cleaner.

**Comment by azdle** [comment]
> I think that one hash table lookup in a small, in-cache table for some messages is probably a bit cheaper than system-timestamp generation all the time. This is in no small part because getting the system time likely involves a syscall, and (even an efficient syscall that elides mode switches in some cases) is far from a free copy.

I was assuming that getting time would be faster than the hash lookup. Though I'd probably trust your intuition on that over mine.

> However, I don't think we can trivially replace the existing `tick` which uses `Instant` with a `SystemTime` based timestamp since `SystemTime` does not have the property of being monotonic, and we require monotonic ticks for event ordering in the ingest protocol.

Ah, that's something I definitely overlooked. I didn't really take note of the fact that this was using SystemTime and was assuming we could compute both `tick` and `timestamp` on the other end with a single value from the traced thread.

> That said, it's probably pretty close on perf and there's something to be said for being cleaner.

I don't have a super strong opinion one way or the other, especially if the unconditional grabbing of time isn't faster. I'll leave the choice up to you.

**Review by azdle — APPROVED** [review]

**Comment by ZackPierce** [comment]
Ended up doing the unconditional time-grab for simplicity's sake.

**Pull request merged**
